name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t borjanob/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true borjanob/react-test npm test
 
      - run: docker build -t borjanob/multi-client-10-14:latest ./client
      - run: docker build -t borjanob/multi-nginx-10-14:latest ./nginx
      - run: docker build -t borjanob/multi-server-10-14:latest ./server
      - run: docker build -t borjanob/multi-worker-10-14:latest ./worker
 
      - run: docker push borjanob/multi-client-10-14:latest
      - run: docker push borjanob/multi-nginx-10-14:latest
      - run: docker push borjanob/multi-server-10-14:latest
      - run: docker push borjanob/multi-worker-10-14:latest
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-753150288944
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip